'use client'

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Download, FileText, Mail, Share2, Copy } from 'lucide-react'
import { useState } from 'react'

interface UserProfile {
  education: string
  skills: string[]
  interests: string[]
  industry: string
  personality: string
}

interface Recommendation {
  name: string
  matchPercentage: number
  description: string
  salaryRange: string
  whyRecommended: string
}

interface ExportReportProps {
  userProfile: UserProfile
  recommendations: Recommendation[]
  savedCareers: string[]
}

export default function ExportReport({
  userProfile,
  recommendations,
  savedCareers,
}: ExportReportProps) {
  const [copiedReport, setCopiedReport] = useState(false)

  const generateTextReport = () => {
    const report = `
CELESTIAL CAREER HUB - PROFESSIONAL CAREER REPORT
Generated: ${new Date().toLocaleDateString()}

=== YOUR PROFILE ===
Education: ${userProfile.education}
Skills: ${userProfile.skills.join(', ')}
Interests: ${userProfile.interests.join(', ')}
Preferred Industry: ${userProfile.industry}
Personality Type: ${userProfile.personality}

=== TOP CAREER RECOMMENDATIONS ===
${recommendations
  .slice(0, 5)
  .map(
    (career, idx) => `
${idx + 1}. ${career.name} (${career.matchPercentage}% Match)
   Salary Range: ${career.salaryRange}
   Description: ${career.description}
   Why Recommended: ${career.whyRecommended}
`
  )
  .join('')}

=== SAVED CAREERS ===
${savedCareers.length > 0 ? savedCareers.join('\n') : 'No careers saved yet'}

=== ACTION ITEMS ===
1. Review your top 3 career matches
2. Develop missing skills identified
3. Connect with industry mentors
4. Prepare for interviews using our prep guide
5. Research salary negotiation strategies

Generated by Celestial Career Hub
    `.trim()

    return report
  }

  const handleDownloadPDF = () => {
    const report = generateTextReport()
    const element = document.createElement('a')
    const file = new Blob([report], { type: 'text/plain' })
    element.href = URL.createObjectURL(file)
    element.download = `career-report-${Date.now()}.txt`
    document.body.appendChild(element)
    element.click()
    document.body.removeChild(element)
  }

  const handleCopyReport = () => {
    const report = generateTextReport()
    navigator.clipboard.writeText(report)
    setCopiedReport(true)
    setTimeout(() => setCopiedReport(false), 2000)
  }

  const handleEmailReport = () => {
    const report = generateTextReport()
    const subject = 'My Celestial Career Hub Report'
    const body = encodeURIComponent(report)
    window.location.href = `mailto:?subject=${subject}&body=${body}`
  }

  return (
    <div className="space-y-6">
      <div className="grid md:grid-cols-2 gap-4">
        <Card className="card-professional">
          <CardHeader>
            <CardTitle className="text-lg flex items-center gap-2">
              <FileText className="w-5 h-5" />
              Quick Export
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-3">
            <Button
              onClick={handleDownloadPDF}
              className="w-full bg-purple-600 hover:bg-purple-700 text-white flex items-center justify-center gap-2"
            >
              <Download className="w-4 h-4" />
              Download as Text
            </Button>
            <Button
              onClick={handleCopyReport}
              variant="outline"
              className="w-full cosmic-border flex items-center justify-center gap-2 bg-transparent"
            >
              <Copy className="w-4 h-4" />
              {copiedReport ? 'Copied!' : 'Copy to Clipboard'}
            </Button>
            <Button
              onClick={handleEmailReport}
              variant="outline"
              className="w-full cosmic-border flex items-center justify-center gap-2 bg-transparent"
            >
              <Mail className="w-4 h-4" />
              Email Report
            </Button>
          </CardContent>
        </Card>

        <Card className="card-professional">
          <CardHeader>
            <CardTitle className="text-lg flex items-center gap-2">
              <Share2 className="w-5 h-5" />
              Report Summary
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-3 text-sm">
            <div className="flex justify-between">
              <span className="text-muted-foreground">Top Matches</span>
              <span className="font-semibold">{recommendations.length}</span>
            </div>
            <div className="flex justify-between">
              <span className="text-muted-foreground">Saved Careers</span>
              <span className="font-semibold">{savedCareers.length}</span>
            </div>
            <div className="flex justify-between">
              <span className="text-muted-foreground">Your Skills</span>
              <span className="font-semibold">{userProfile.skills.length}</span>
            </div>
            <div className="flex justify-between">
              <span className="text-muted-foreground">Avg Readiness</span>
              <span className="font-semibold">
                {Math.round(
                  recommendations.reduce((sum, r) => sum + r.matchPercentage, 0) /
                    recommendations.length
                )}
                %
              </span>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Detailed Report Preview */}
      <Card className="card-professional">
        <CardHeader>
          <CardTitle className="text-lg">Full Report Preview</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="bg-background/50 rounded-lg p-6 font-mono text-xs overflow-auto max-h-96 border border-purple-900/30">
            <pre className="text-muted-foreground whitespace-pre-wrap break-words">
              {generateTextReport()}
            </pre>
          </div>
        </CardContent>
      </Card>

      {/* Top Recommendations Card */}
      <Card className="card-professional">
        <CardHeader>
          <CardTitle className="text-lg">Your Top Recommendations</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="space-y-3">
            {recommendations.slice(0, 5).map((career, idx) => (
              <div
                key={idx}
                className="p-4 rounded-lg bg-purple-900/20 border border-purple-500/30 space-y-2"
              >
                <div className="flex items-center justify-between">
                  <h4 className="font-semibold">{career.name}</h4>
                  <Badge className="bg-gradient-to-r from-purple-600 to-pink-600">
                    {career.matchPercentage}%
                  </Badge>
                </div>
                <p className="text-sm text-muted-foreground">{career.description}</p>
                <div className="flex items-center justify-between text-xs">
                  <span className="text-muted-foreground">Salary: {career.salaryRange}</span>
                  {savedCareers.includes(career.name) && (
                    <Badge variant="secondary" className="bg-green-900/30 text-green-300">
                      Saved
                    </Badge>
                  )}
                </div>
              </div>
            ))}
          </div>
        </CardContent>
      </Card>

      {/* User Profile Summary */}
      <Card className="card-professional">
        <CardHeader>
          <CardTitle className="text-lg">Your Profile</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div>
            <h4 className="font-semibold text-sm mb-2">Education Level</h4>
            <Badge className="bg-purple-600">{userProfile.education}</Badge>
          </div>
          <div>
            <h4 className="font-semibold text-sm mb-2">Current Skills ({userProfile.skills.length})</h4>
            <div className="flex flex-wrap gap-2">
              {userProfile.skills.map((skill) => (
                <Badge key={skill} variant="secondary" className="cosmic-border">
                  {skill}
                </Badge>
              ))}
            </div>
          </div>
          <div>
            <h4 className="font-semibold text-sm mb-2">Interests ({userProfile.interests.length})</h4>
            <div className="flex flex-wrap gap-2">
              {userProfile.interests.map((interest) => (
                <Badge key={interest} variant="secondary" className="cosmic-border">
                  {interest}
                </Badge>
              ))}
            </div>
          </div>
          <div>
            <h4 className="font-semibold text-sm mb-2">Industry Preference</h4>
            <Badge className="bg-blue-600">{userProfile.industry}</Badge>
          </div>
          <div>
            <h4 className="font-semibold text-sm mb-2">Personality Type</h4>
            <Badge className="bg-pink-600">{userProfile.personality}</Badge>
          </div>
        </CardContent>
      </Card>
    </div>
  )
}
